config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :listings
  resources :categories
  
  namespace :my_account do
    resources :listings
  end

  namespace :admin do
    resources :categories
  end

  get 'pages/about'
  get 'pages/contact'

  root 'listings#index'

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	validates :name, :destription, :price, presence: true
	validates :price, numericality: {greater_than: 0}

	belongs_to :user
	belongs_to :category

	mount_uploader :image, ImageUploader
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    category = params[:category]
    if category.blank?
      @listings = Listing.all.paginate(page: params[:page], per_page: 4)
    else
      @listings = Listing.where(category_id: Category.where(name: category).select(:id)).paginate(page: params[:page], per_page: 4)
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    @listing.user = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def check_user
      unless current_user == @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :destription, :price, :image, :category_id)
    end
end

app/controllers/my_account/listings_controller.rb
class MyAccount::ListingsController < ApplicationController

	before_action :authenticate_user!

	def index
		@listings = Listing.where(user: current_user);
	end
end

app/helpers/listings_helper.rb
module ListingsHelper

	# check if the listing belongs to current user who is logged in
	def belongs_to_current_user?(listing)
		if user_signed_in? && current_user == listing.user
			return true
		end
		false
	end
end

app/helpers/my_account/listings_helper.rb
module MyAccount::ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing, html: {multipart: true}) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</strong>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %><br/>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category"}, {class: 'btn btn-sm btn-default dropdown-toggle'} %>
  </div>

  <div class="form-group">
    <%= f.label :destription %><br>
    <%= f.text_area :destription, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label 'Image File' %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: 'btn btn-link' %> | <%= link_to 'Back', listings_path, class: 'btn btn-link' %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Listings</h1>

<div class="row center">
  <% @listings.each do |listing| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag(listing.image_url(:medium), alt: listing.name, class: 'img-rounded' ), listing %>


        <div class="caption">
          <h3><%= listing.name %></h3>
          <p><%= number_to_currency listing.price %></p>
          <p><%= listing.destription %></p>
          <% if belongs_to_current_user? listing %>
            <p>
              <%= link_to 'Edit', edit_listing_path(listing), class: 'btn btn-default btn-in-grid'  %>
              <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-in-grid'  %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>
<%= will_paginate @listings, renderer: BootstrapPagination::Rails%> <br/>
<%= link_to 'New Listing', new_listing_path, class: 'btn btn-link' %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: 'btn btn-link' %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
			<%= image_tag @listing.image_url %>
		</div>		
	</div>
	<div class="col-md-6">
		<h5>
		  <%= @listing.name %>
		</h5>

		<p>
		  <strong>Destription:</strong>
		  <%= @listing.destription %>
		</p>

		<p>
		  <strong>Price:</strong>
		  <%= number_to_currency @listing.price %>
		</p>
	</div>
</div>

<% if belongs_to_current_user? @listing %>
	<%= link_to 'Edit', edit_listing_path(@listing) %> |
<% end %>
<%= link_to 'Back', listings_path %>